name: ThaneBukkit
main: org.thane.ThaneBukkit
version: 0.1
author: GreatThane
commands:
   sethunger:
      description: Sets hunger of targeted player.
      usage: §c/sethunger <player> <value>
      permission: ThaneBukkit.sethunger
      permission-message: You don't have <permission>