name: ThaneBukkit
main: org.thane.ThaneBukkit
version: 0.1
depend: [WorldGuard]
author: GreatThane
commands:
   sethunger:
      description: Sets hunger of targeted player.
      usage: §c/sethunger <player> <value>
      permission: ThaneBukkit.sethunger
      permission-message: You don't have <permission>
   timer:
      description: A minute and second timer.
      usage: §c/timer <player> <start|stop> [x,y,z]
      permission: ThaneBukkit.timer
      permisssion-message: You don't have <permission>
   survivorminer:
      description: Plugin for the Survivor Miner game.
      usage: §c/survivorminer <start|stop>
      permission: ThaneBukkit.survivorminer
      permission-message: You don't have <permission>
   animate:
      description: Command to animte a series of blocks.
      usage: §c/animate <target x,y,z> <reference x1,y1,z1> < reference x2,y2,z2> <direction> <# of frames> <distance between frames> <fps>
      permission: ThaneBukkit.animate
      permission-message: You don't have <permission>
   optool:
      description: Developer command
      usage: §c/optool <currency> <value>
      permission: ThaneBukkit.optool
      permission-message: You don't have <permission>
   thanereload:
      description: Reload the plugin
      usage: §c/thanereload
      permission: ThaneBukkit.reload
      permission-message: You don't have <permission>
   zombiebuy:
      description: Buy an item from the shop.
      usage: §c/zombiebuy <item|enchantment> <player>
      permission: ThaneBukkit.zombiebuy
      permission-message: You don't have <permission>
   pvp:
      description: Begin or end a Player Vs Parkour game.
      usage: §c/pvp <start|stop>
      permission: ThaneBukkit.pvp
      permission-message: You don't have <permission>